install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew update && brew upgrade python3; fi
  - pip install jsonschema
  - curl https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/schema-draft-v4.json > schema.json

script:
  - jsonschema schema.json -i gnds-2.0.json

language: python

os:
  - linux
  - osx
